"""
setup_files.py — Rewrites all corrupted honeypot files cleanly.
Run: python setup_files.py
"""
from pathlib import Path

def write(path, content):
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f"  created: {path}")

print("\nRewriting all honeypot files...\n")

# ── capture/__init__.py ───────────────────────────────────────────────────────
write('capture/__init__.py', '# capture package\n')

# ── honeypots/__init__.py ─────────────────────────────────────────────────────
write('honeypots/__init__.py', '# honeypots package\n')

# ── capture/logger.py ─────────────────────────────────────────────────────────
write('capture/logger.py', '\n'.join([
    'import json, logging, threading',
    'from datetime import datetime, timezone',
    'from pathlib import Path',
    'import colorlog',
    '',
    'try:',
    '    from config import LOG_DIR, LOG_FILE',
    'except ImportError:',
    '    LOG_DIR  = Path("logs")',
    '    LOG_FILE = LOG_DIR / "attacks.jsonl"',
    '',
    'Path(LOG_DIR).mkdir(parents=True, exist_ok=True)',
    '_file_lock = threading.Lock()',
    '',
    '_handler = colorlog.StreamHandler()',
    '_handler.setFormatter(colorlog.ColoredFormatter(',
    '    fmt="%(log_color)s%(asctime)s%(reset)s [%(log_color)s%(levelname)-8s%(reset)s] %(cyan)s%(name)-10s%(reset)s %(message)s",',
    '    datefmt="%Y-%m-%d %H:%M:%S",',
    '    log_colors={"DEBUG":"white","INFO":"green","WARNING":"yellow","ERROR":"red","CRITICAL":"bold_red"}',
    '))',
    'logging.basicConfig(level=logging.INFO, handlers=[_handler])',
    '',
    'def get_logger(name: str):',
    '    return logging.getLogger(name)',
    '',
    'def log_event(service, attacker_ip, attacker_port, event_type, details=None):',
    '    event = {',
    '        "timestamp"    : datetime.now(timezone.utc).isoformat(),',
    '        "service"      : service,',
    '        "attacker_ip"  : attacker_ip,',
    '        "attacker_port": attacker_port,',
    '        "event_type"   : event_type,',
    '        "details"      : details or {},',
    '    }',
    '    with _file_lock:',
    '        with open(LOG_FILE, "a", encoding="utf-8") as f:',
    '            f.write(json.dumps(event) + "\\n")',
    '    get_logger(service).info(f"[{event_type}] {attacker_ip}:{attacker_port} | {details}")',
    '    return event',
    '',
]))

# ── honeypots/ssh_honeypot.py ─────────────────────────────────────────────────
write('honeypots/ssh_honeypot.py', '\n'.join([
    'import socket, threading, time',
    'import paramiko',
    'from capture.logger import log_event, get_logger',
    'from config import HOST, SSH_PORT, SSH_BANNER, AUTH_DELAY_SECONDS, SESSION_TIMEOUT',
    '',
    'logger   = get_logger("SSH")',
    'HOST_KEY = paramiko.RSAKey.generate(2048)',
    '',
    'class SSHHoneypotServer(paramiko.ServerInterface):',
    '    def __init__(self, ip, port):',
    '        self.client_ip   = ip',
    '        self.client_port = port',
    '        self.shell_event = threading.Event()',
    '    def check_channel_request(self, kind, chanid):',
    '        return paramiko.OPEN_SUCCEEDED if kind == "session" else paramiko.OPEN_FAILED_ADMINISTRATIVELY_PROHIBITED',
    '    def check_channel_shell_request(self, channel):',
    '        self.shell_event.set(); return True',
    '    def check_channel_pty_request(self, channel, term, width, height, pixelwidth, pixelheight, modes):',
    '        return True',
    '    def check_auth_password(self, username, password):',
    '        time.sleep(AUTH_DELAY_SECONDS)',
    '        log_event("SSH", self.client_ip, self.client_port, "AUTH_ATTEMPT",',
    '                  {"username": username, "password": password, "method": "password"})',
    '        return paramiko.AUTH_FAILED',
    '    def check_auth_publickey(self, username, key):',
    '        log_event("SSH", self.client_ip, self.client_port, "AUTH_ATTEMPT",',
    '                  {"username": username, "key_type": key.get_name(), "method": "publickey"})',
    '        return paramiko.AUTH_FAILED',
    '    def get_allowed_auths(self, username): return "password,publickey"',
    '',
    'def _handle_client(sock, addr):',
    '    ip, port = addr',
    '    log_event("SSH", ip, port, "CONNECTION", {"status": "connected"})',
    '    transport = None',
    '    try:',
    '        transport = paramiko.Transport(sock)',
    '        transport.local_version = SSH_BANNER',
    '        transport.add_server_key(HOST_KEY)',
    '        server = SSHHoneypotServer(ip, port)',
    '        try: transport.start_server(server=server)',
    '        except paramiko.SSHException: return',
    '        channel = transport.accept(SESSION_TIMEOUT)',
    '        if channel:',
    '            channel.send(b"\\r\\nWelcome to Ubuntu 22.04\\r\\nroot@ubuntu:~# ")',
    '            server.shell_event.wait(SESSION_TIMEOUT)',
    '            channel.settimeout(SESSION_TIMEOUT)',
    '            try:',
    '                while True:',
    '                    data = channel.recv(4096)',
    '                    if not data: break',
    '                    cmd = data.decode("utf-8", errors="ignore").strip()',
    '                    if cmd:',
    '                        log_event("SSH", ip, port, "COMMAND", {"command": cmd})',
    '                    channel.send(f"\\r\\nbash: {cmd}: command not found\\r\\nroot@ubuntu:~# ".encode())',
    '            except socket.timeout: pass',
    '            finally: channel.close()',
    '    except Exception as e: logger.debug(f"SSH error {ip}: {e}")',
    '    finally:',
    '        if transport:',
    '            try: transport.close()',
    '            except: pass',
    '        try: sock.close()',
    '        except: pass',
    '        log_event("SSH", ip, port, "DISCONNECTION", {})',
    '',
    'def start_ssh_honeypot():',
    '    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)',
    '    s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)',
    '    try: s.bind((HOST, SSH_PORT))',
    '    except PermissionError:',
    '        logger.error(f"Cannot bind port {SSH_PORT}. Use sudo for ports < 1024."); return',
    '    s.listen(128)',
    '    logger.info(f"SSH Honeypot listening on {HOST}:{SSH_PORT}")',
    '    while True:',
    '        try:',
    '            client, addr = s.accept()',
    '            threading.Thread(target=_handle_client, args=(client, addr), daemon=True).start()',
    '        except Exception as e: logger.error(f"SSH accept error: {e}")',
    '',
]))

# ── honeypots/http_honeypot.py ────────────────────────────────────────────────
write('honeypots/http_honeypot.py', '\n'.join([
    'from flask import Flask, request, make_response',
    'from capture.logger import log_event, get_logger',
    'from config import HOST, HTTP_PORT, HTTP_SERVER_HEADER, HTTP_POWERED_BY',
    '',
    'logger = get_logger("HTTP")',
    'app    = Flask(__name__)',
    'app.config["PROPAGATE_EXCEPTIONS"] = False',
    '',
    '_SQLI = ["1=1","OR 1","SELECT","UNION","DROP","INSERT","UPDATE","DELETE","EXEC","--","/*"]',
    '_ADMIN = {"/admin","/wp-admin","/wp-login.php","/phpmyadmin","/login","/administrator"}',
    '',
    'def _detect(path, body, args):',
    '    full = (path + str(args) + body).upper()',
    '    if "../" in path or "..%2f" in path.lower(): return "PATH_TRAVERSAL"',
    '    if any(p.upper() in full for p in _SQLI): return "SQLI_ATTEMPT"',
    '    if any(path.rstrip("/").lower().startswith(a) for a in _ADMIN): return "ADMIN_ACCESS"',
    '    return "REQUEST"',
    '',
    'def _resp(body, status=200):',
    '    r = make_response(body, status)',
    '    r.headers["Server"]       = HTTP_SERVER_HEADER',
    '    r.headers["X-Powered-By"] = HTTP_POWERED_BY',
    '    return r',
    '',
    'LOGIN_PAGE = """<!DOCTYPE html><html><head><title>Login</title></head><body>',
    '<h2>System Login</h2><form method="POST">',
    'Username: <input name="username"><br>',
    'Password: <input type="password" name="password"><br>',
    '<input type="submit" value="Login"></form>{error}</body></html>"""',
    '',
    '@app.route("/wp-login.php", methods=["GET","POST"])',
    '@app.route("/admin", methods=["GET","POST"])',
    '@app.route("/login", methods=["GET","POST"])',
    'def login():',
    '    if request.method == "POST":',
    '        log_event("HTTP", request.remote_addr, 0, "CREDENTIAL_ATTEMPT",',
    '                  {"username": request.form.get("username",""), "password": request.form.get("password","")})',
    '        return _resp(LOGIN_PAGE.format(error="<p style=color:red>Invalid credentials.</p>"), 401)',
    '    log_event("HTTP", request.remote_addr, 0, "ADMIN_ACCESS", {"path": request.path})',
    '    return _resp(LOGIN_PAGE.format(error=""))',
    '',
    '@app.route("/", defaults={"path":""}, methods=["GET","POST","PUT","DELETE","OPTIONS","HEAD"])',
    '@app.route("/<path:path>",            methods=["GET","POST","PUT","DELETE","OPTIONS","HEAD"])',
    'def catch_all(path):',
    '    body = request.get_data(as_text=True)',
    '    et   = _detect(request.path, body, dict(request.args))',
    '    log_event("HTTP", request.remote_addr, 0, et,',
    '              {"method": request.method, "path": request.path,',
    '               "user_agent": request.headers.get("User-Agent",""), "body": body[:500]})',
    '    return _resp("<h1>404 Not Found</h1>", 404)',
    '',
    'def start_http_honeypot():',
    '    logger.info(f"HTTP Honeypot listening on {HOST}:{HTTP_PORT}")',
    '    app.run(host=HOST, port=HTTP_PORT, threaded=True, use_reloader=False, debug=False)',
    '',
]))

# ── honeypots/ftp_honeypot.py ─────────────────────────────────────────────────
write('honeypots/ftp_honeypot.py', '\n'.join([
    'import logging',
    'from pyftpdlib.handlers   import FTPHandler',
    'from pyftpdlib.servers    import FTPServer',
    'from pyftpdlib.authorizers import DummyAuthorizer',
    'from capture.logger import log_event, get_logger',
    'from config import HOST, FTP_PORT, FTP_BANNER, MAX_LOGIN_ATTEMPTS',
    '',
    'logger = get_logger("FTP")',
    'logging.getLogger("pyftpdlib").setLevel(logging.WARNING)',
    '',
    'class HoneypotFTPHandler(FTPHandler):',
    '    def on_connect(self):',
    '        log_event("FTP", self.remote_ip, self.remote_port, "CONNECTION", {"status": "connected"})',
    '    def on_disconnect(self):',
    '        log_event("FTP", self.remote_ip, self.remote_port, "DISCONNECTION", {})',
    '    def on_login_failed(self, username, password):',
    '        log_event("FTP", self.remote_ip, self.remote_port, "AUTH_ATTEMPT",',
    '                  {"username": username, "password": password, "result": "failed"})',
    '    def on_login(self, username):',
    '        log_event("FTP", self.remote_ip, self.remote_port, "AUTH_SUCCESS", {"username": username})',
    '    def on_file_received(self, file):',
    '        log_event("FTP", self.remote_ip, self.remote_port, "FILE_UPLOAD", {"file": file})',
    '    def on_file_sent(self, file):',
    '        log_event("FTP", self.remote_ip, self.remote_port, "FILE_DOWNLOAD", {"file": file})',
    '',
    'def start_ftp_honeypot():',
    '    auth = DummyAuthorizer()',
    '    auth.add_anonymous("/tmp", perm="elradfmwMT")',
    '    HoneypotFTPHandler.authorizer       = auth',
    '    HoneypotFTPHandler.banner           = FTP_BANNER',
    '    HoneypotFTPHandler.passive_ports    = range(60000, 60100)',
    '    HoneypotFTPHandler.max_login_attempts = MAX_LOGIN_ATTEMPTS',
    '    srv = FTPServer((HOST, FTP_PORT), HoneypotFTPHandler)',
    '    srv.max_cons = 50',
    '    logger.info(f"FTP Honeypot listening on {HOST}:{FTP_PORT}")',
    '    srv.serve_forever()',
    '',
]))

# ── honeypots/telnet_honeypot.py ──────────────────────────────────────────────
write('honeypots/telnet_honeypot.py', '\n'.join([
    'import socket, threading, time',
    'from capture.logger import log_event, get_logger',
    'from config import HOST, TELNET_PORT, TELNET_BANNER, AUTH_DELAY_SECONDS, MAX_LOGIN_ATTEMPTS, SESSION_TIMEOUT',
    '',
    'logger = get_logger("TELNET")',
    '',
    'def _strip(data):',
    '    result, i = bytearray(), 0',
    '    while i < len(data):',
    '        if data[i] == 0xFF and i+2 < len(data): i += 3',
    '        else: result.append(data[i]); i += 1',
    '    return result.decode("utf-8", errors="ignore").strip()',
    '',
    'def _recv(sock, timeout=30.0):',
    '    sock.settimeout(timeout)',
    '    buf = b""',
    '    try:',
    '        while True:',
    '            chunk = sock.recv(256)',
    '            if not chunk: break',
    '            buf += chunk',
    '            if b"\\n" in buf or b"\\r" in buf: break',
    '    except (socket.timeout, OSError): pass',
    '    return _strip(buf)',
    '',
    'def _handle(sock, addr):',
    '    ip, port = addr',
    '    log_event("TELNET", ip, port, "CONNECTION", {"status": "connected"})',
    '    try:',
    '        sock.send(TELNET_BANNER.encode())',
    '        for attempt in range(1, MAX_LOGIN_ATTEMPTS+1):',
    '            username = _recv(sock, SESSION_TIMEOUT)',
    '            if not username: break',
    '            sock.send(b"Password: ")',
    '            password = _recv(sock, SESSION_TIMEOUT)',
    '            log_event("TELNET", ip, port, "AUTH_ATTEMPT",',
    '                      {"username": username, "password": password, "attempt": attempt})',
    '            time.sleep(AUTH_DELAY_SECONDS)',
    '            if attempt < MAX_LOGIN_ATTEMPTS:',
    '                sock.send(b"\\r\\nLogin incorrect\\r\\n\\r\\n")',
    '                sock.send(TELNET_BANNER.encode())',
    '            else:',
    '                sock.send(b"\\r\\nLogin incorrect\\r\\nConnection closed.\\r\\n")',
    '    except (BrokenPipeError, ConnectionResetError, OSError): pass',
    '    finally:',
    '        try: sock.close()',
    '        except: pass',
    '        log_event("TELNET", ip, port, "DISCONNECTION", {})',
    '',
    'def start_telnet_honeypot():',
    '    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)',
    '    s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)',
    '    try: s.bind((HOST, TELNET_PORT))',
    '    except PermissionError:',
    '        logger.error(f"Cannot bind port {TELNET_PORT}. Use sudo for ports < 1024."); return',
    '    s.listen(128)',
    '    logger.info(f"Telnet Honeypot listening on {HOST}:{TELNET_PORT}")',
    '    while True:',
    '        try:',
    '            client, addr = s.accept()',
    '            threading.Thread(target=_handle, args=(client, addr), daemon=True).start()',
    '        except Exception as e: logger.error(f"Telnet error: {e}")',
    '',
]))

print("\nAll files rewritten successfully!")
print("Now run: python main.py\n")
