"""
setup_phase2.py — Writes all Phase 2 files cleanly.
Run: python setup_phase2.py
"""
from pathlib import Path

def write(path, content):
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f"  created: {path}")

print("\nWriting Phase 2 files...\n")

# ── capture/database.py ───────────────────────────────────────────────────────
write('capture/database.py', '\n'.join([
    '"""',
    'capture/database.py — SQLite database layer.',
    'Creates the database schema and provides functions',
    'to save and query honeypot events.',
    '"""',
    'import json',
    'from datetime import datetime',
    'from sqlalchemy import (create_engine, Column, Integer, String,',
    '                        Float, Text, DateTime, Index)',
    'from sqlalchemy.orm import declarative_base, sessionmaker',
    '',
    'try:',
    '    from config import DB_PATH',
    'except ImportError:',
    '    from pathlib import Path',
    '    DB_PATH = Path("data/honeypot.db")',
    '',
    'Base    = declarative_base()',
    'engine  = create_engine(f"sqlite:///{DB_PATH}", connect_args={"check_same_thread": False})',
    'Session = sessionmaker(bind=engine)',
    '',
    '',
    'class AttackEvent(Base):',
    '    """One row per honeypot event."""',
    '    __tablename__ = "attack_events"',
    '',
    '    id            = Column(Integer, primary_key=True, autoincrement=True)',
    '    timestamp     = Column(DateTime, default=datetime.utcnow, nullable=False)',
    '    service       = Column(String(16),  nullable=False)',
    '    attacker_ip   = Column(String(45),  nullable=False)',
    '    attacker_port = Column(Integer,     nullable=False)',
    '    event_type    = Column(String(32),  nullable=False)',
    '    details       = Column(Text,        default="{}")',
    '',
    '    # ── Feature columns (filled by feature extractor) ──────────────────',
    '    username      = Column(String(128), nullable=True)',
    '    password      = Column(String(256), nullable=True)',
    '    password_len  = Column(Integer,     nullable=True)',
    '    http_method   = Column(String(10),  nullable=True)',
    '    http_path     = Column(String(512), nullable=True)',
    '    user_agent    = Column(String(512), nullable=True)',
    '    payload       = Column(Text,        nullable=True)',
    '',
    '    # ── ML label (filled after classification) ─────────────────────────',
    '    attack_label  = Column(Integer,     nullable=True)',
    '    attack_name   = Column(String(64),  nullable=True)',
    '',
    '    __table_args__ = (',
    '        Index("ix_ip",        "attacker_ip"),',
    '        Index("ix_service",   "service"),',
    '        Index("ix_event",     "event_type"),',
    '        Index("ix_timestamp", "timestamp"),',
    '    )',
    '',
    '    def to_dict(self):',
    '        return {',
    '            "id"           : self.id,',
    '            "timestamp"    : str(self.timestamp),',
    '            "service"      : self.service,',
    '            "attacker_ip"  : self.attacker_ip,',
    '            "attacker_port": self.attacker_port,',
    '            "event_type"   : self.event_type,',
    '            "username"     : self.username,',
    '            "password"     : self.password,',
    '            "password_len" : self.password_len,',
    '            "http_method"  : self.http_method,',
    '            "http_path"    : self.http_path,',
    '            "user_agent"   : self.user_agent,',
    '            "attack_label" : self.attack_label,',
    '            "attack_name"  : self.attack_name,',
    '        }',
    '',
    '',
    'def init_db():',
    '    """Create all tables if they do not exist."""',
    '    Base.metadata.create_all(engine)',
    '',
    '',
    'def save_event(event: dict) -> AttackEvent:',
    '    """',
    '    Persist a honeypot event dict to the database.',
    '    Returns the saved AttackEvent ORM object.',
    '    """',
    '    details = event.get("details", {})',
    '    ts_raw  = event.get("timestamp")',
    '    try:',
    '        from datetime import timezone',
    '        ts = datetime.fromisoformat(ts_raw).replace(tzinfo=None) if ts_raw else datetime.utcnow()',
    '    except Exception:',
    '        ts = datetime.utcnow()',
    '',
    '    row = AttackEvent(',
    '        timestamp     = ts,',
    '        service       = event.get("service", ""),',
    '        attacker_ip   = event.get("attacker_ip", ""),',
    '        attacker_port = event.get("attacker_port", 0),',
    '        event_type    = event.get("event_type", ""),',
    '        details       = json.dumps(details),',
    '        username      = details.get("username"),',
    '        password      = details.get("password"),',
    '        password_len  = len(details["password"]) if details.get("password") else None,',
    '        http_method   = details.get("method"),',
    '        http_path     = details.get("path"),',
    '        user_agent    = details.get("user_agent"),',
    '        payload       = details.get("body") or details.get("command"),',
    '    )',
    '    session = Session()',
    '    try:',
    '        session.add(row)',
    '        session.commit()',
    '        session.refresh(row)',
    '        return row',
    '    except Exception as e:',
    '        session.rollback()',
    '        raise e',
    '    finally:',
    '        session.close()',
    '',
    '',
    'def get_recent_events(limit: int = 100) -> list:',
    '    """Return the most recent N events as dicts."""',
    '    session = Session()',
    '    try:',
    '        rows = (session.query(AttackEvent)',
    '                .order_by(AttackEvent.id.desc())',
    '                .limit(limit).all())',
    '        return [r.to_dict() for r in rows]',
    '    finally:',
    '        session.close()',
    '',
    '',
    'def get_stats() -> dict:',
    '    """Return summary statistics for the dashboard."""',
    '    session = Session()',
    '    try:',
    '        from sqlalchemy import func',
    '        total   = session.query(func.count(AttackEvent.id)).scalar()',
    '        by_svc  = dict(session.query(AttackEvent.service,',
    '                       func.count(AttackEvent.id))',
    '                       .group_by(AttackEvent.service).all())',
    '        by_type = dict(session.query(AttackEvent.event_type,',
    '                       func.count(AttackEvent.id))',
    '                       .group_by(AttackEvent.event_type).all())',
    '        by_ip   = dict(session.query(AttackEvent.attacker_ip,',
    '                       func.count(AttackEvent.id))',
    '                       .group_by(AttackEvent.attacker_ip)',
    '                       .order_by(func.count(AttackEvent.id).desc())',
    '                       .limit(10).all())',
    '        return {"total": total, "by_service": by_svc,',
    '                "by_event_type": by_type, "top_ips": by_ip}',
    '    finally:',
    '        session.close()',
    '',
    '',
    '# Auto-initialise on import',
    'init_db()',
]))

# ── capture/feature_extractor.py ──────────────────────────────────────────────
write('capture/feature_extractor.py', '\n'.join([
    '"""',
    'capture/feature_extractor.py — Converts raw honeypot events',
    'into numerical feature vectors ready for ML training.',
    '',
    'Feature vector (14 features):',
    '  0  service_ssh        — 1 if SSH, else 0',
    '  1  service_http       — 1 if HTTP, else 0',
    '  2  service_ftp        — 1 if FTP, else 0',
    '  3  service_telnet     — 1 if TELNET, else 0',
    '  4  is_auth_attempt    — 1 if AUTH_ATTEMPT / CREDENTIAL_ATTEMPT',
    '  5  is_admin_access    — 1 if ADMIN_ACCESS',
    '  6  is_sqli            — 1 if SQLI_ATTEMPT',
    '  7  is_path_traversal  — 1 if PATH_TRAVERSAL',
    '  8  is_command         — 1 if COMMAND',
    '  9  password_len       — length of password (0 if none)',
    '  10 username_is_root   — 1 if username is root/admin/administrator',
    '  11 has_sqli_chars     — 1 if payload contains SQL chars',
    '  12 has_traversal      — 1 if payload contains ../',
    '  13 payload_len        — length of payload/body (0 if none)',
    '"""',
    '',
    'import json',
    'import re',
    '',
    'FEATURE_NAMES = [',
    '    "service_ssh", "service_http", "service_ftp", "service_telnet",',
    '    "is_auth_attempt", "is_admin_access", "is_sqli", "is_path_traversal",',
    '    "is_command", "password_len", "username_is_root",',
    '    "has_sqli_chars", "has_traversal", "payload_len",',
    ']',
    '',
    '_SQLI_RE      = re.compile(r"(\'|\"|\-\-|;|union|select|drop|insert|update|delete|exec|cast)",',
    '                            re.IGNORECASE)',
    '_TRAVERSAL_RE = re.compile(r"\.\./|\.\.\\\\", re.IGNORECASE)',
    '_ROOT_USERS   = {"root", "admin", "administrator", "superuser", "sa", "postgres"}',
    '',
    '',
    'def extract(event: dict) -> list:',
    '    """',
    '    Takes a raw event dict and returns a list of 14 numeric features.',
    '    """',
    '    service    = event.get("service", "").upper()',
    '    event_type = event.get("event_type", "").upper()',
    '    details    = event.get("details", {})',
    '    if isinstance(details, str):',
    '        try: details = json.loads(details)',
    '        except: details = {}',
    '',
    '    username = str(details.get("username") or "").lower()',
    '    password = str(details.get("password") or "")',
    '    payload  = str(',
    '        details.get("body") or',
    '        details.get("command") or',
    '        details.get("path") or ""',
    '    )',
    '',
    '    features = [',
    '        # ── Service one-hot ─────────────────────────────────────────────',
    '        1 if service == "SSH"    else 0,',
    '        1 if service == "HTTP"   else 0,',
    '        1 if service == "FTP"    else 0,',
    '        1 if service == "TELNET" else 0,',
    '',
    '        # ── Event type flags ────────────────────────────────────────────',
    '        1 if event_type in ("AUTH_ATTEMPT", "CREDENTIAL_ATTEMPT") else 0,',
    '        1 if event_type == "ADMIN_ACCESS"    else 0,',
    '        1 if event_type == "SQLI_ATTEMPT"    else 0,',
    '        1 if event_type == "PATH_TRAVERSAL"  else 0,',
    '        1 if event_type == "COMMAND"         else 0,',
    '',
    '        # ── Credential features ─────────────────────────────────────────',
    '        len(password),',
    '        1 if username in _ROOT_USERS else 0,',
    '',
    '        # ── Payload features ────────────────────────────────────────────',
    '        1 if _SQLI_RE.search(payload)      else 0,',
    '        1 if _TRAVERSAL_RE.search(payload) else 0,',
    '        len(payload),',
    '    ]',
    '    return features',
    '',
    '',
    'def extract_batch(events: list) -> list:',
    '    """Extract features from a list of events. Returns list of feature lists."""',
    '    return [extract(e) for e in events]',
    '',
    '',
    'def event_to_row(event: dict) -> dict:',
    '    """Return a flat dict with feature names as keys (for pandas/CSV)."""',
    '    return dict(zip(FEATURE_NAMES, extract(event)))',
]))

# ── capture/exporter.py ───────────────────────────────────────────────────────
write('capture/exporter.py', '\n'.join([
    '"""',
    'capture/exporter.py — Export honeypot database to CSV for ML training.',
    '',
    'Usage:',
    '    python capture/exporter.py',
    '',
    'Produces:',
    '    data/dataset.csv   — feature matrix, one row per event',
    '"""',
    '',
    'import csv',
    'import json',
    'from pathlib import Path',
    '',
    'from capture.database import Session, AttackEvent',
    'from capture.feature_extractor import extract, FEATURE_NAMES',
    '',
    'try:',
    '    from config import ATTACK_LABELS',
    'except ImportError:',
    '    ATTACK_LABELS = {',
    '        0: "Normal",',
    '        1: "Brute Force",',
    '        2: "Port Scan",',
    '        3: "DoS / Flood",',
    '        4: "SQL Injection",',
    '        5: "Command Injection",',
    '        6: "Credential Stuffing",',
    '    }',
    '',
    'OUTPUT_PATH = Path("data/dataset.csv")',
    '',
    '',
    'def _auto_label(event_type: str, details: dict) -> int:',
    '    """',
    '    Automatically assign an attack label based on event type.',
    '    This gives us labelled training data from the honeypot itself.',
    '    """',
    '    et = event_type.upper()',
    '    if et == "SQLI_ATTEMPT":                           return 4',
    '    if et == "COMMAND":                                return 5',
    '    if et == "PATH_TRAVERSAL":                         return 5',
    '    if et in ("AUTH_ATTEMPT", "CREDENTIAL_ATTEMPT"):',
    '        pwd = details.get("password", "")',
    '        if len(str(pwd)) <= 4: return 1   # very short = brute-force default',
    '        return 6                           # longer = credential stuffing',
    '    if et == "ADMIN_ACCESS":                           return 6',
    '    if et == "CONNECTION":                             return 2',
    '    return 0',
    '',
    '',
    'def export_csv(output_path: Path = OUTPUT_PATH) -> int:',
    '    """',
    '    Read all events from the DB, extract features, auto-label,',
    '    and write to CSV. Returns number of rows written.',
    '    """',
    '    output_path.parent.mkdir(parents=True, exist_ok=True)',
    '    session = Session()',
    '    try:',
    '        rows = session.query(AttackEvent).order_by(AttackEvent.id).all()',
    '    finally:',
    '        session.close()',
    '',
    '    if not rows:',
    '        print("No events in database yet. Run the honeypot first.")',
    '        return 0',
    '',
    '    headers = FEATURE_NAMES + ["label", "label_name",',
    '                                "event_type", "service", "attacker_ip"]',
    '',
    '    count = 0',
    '    with open(output_path, "w", newline="", encoding="utf-8") as f:',
    '        writer = csv.writer(f)',
    '        writer.writerow(headers)',
    '',
    '        for row in rows:',
    '            try:',
    '                details = json.loads(row.details) if row.details else {}',
    '            except Exception:',
    '                details = {}',
    '',
    '            event = {',
    '                "service"   : row.service,',
    '                "event_type": row.event_type,',
    '                "details"   : details,',
    '            }',
    '            features   = extract(event)',
    '            label      = _auto_label(row.event_type, details)',
    '            label_name = ATTACK_LABELS.get(label, "Unknown")',
    '',
    '            writer.writerow(',
    '                features + [label, label_name, row.event_type,',
    '                             row.service, row.attacker_ip]',
    '            )',
    '            count += 1',
    '',
    '    print(f"Exported {count} events to {output_path}")',
    '    return count',
    '',
    '',
    'if __name__ == "__main__":',
    '    export_csv()',
]))

# ── Updated capture/logger.py (writes to JSONL + DB) ─────────────────────────
write('capture/logger.py', '\n'.join([
    '"""',
    'capture/logger.py — Shared event logger.',
    'Writes every honeypot event to:',
    '  1. Console  (colorized)',
    '  2. JSONL file (one JSON per line)',
    '  3. SQLite database (via capture.database)',
    '"""',
    'import json, logging, threading',
    'from datetime import datetime, timezone',
    'from pathlib import Path',
    'import colorlog',
    '',
    'try:',
    '    from config import LOG_DIR, LOG_FILE',
    'except ImportError:',
    '    LOG_DIR  = Path("logs")',
    '    LOG_FILE = LOG_DIR / "attacks.jsonl"',
    '',
    'Path(LOG_DIR).mkdir(parents=True, exist_ok=True)',
    '_file_lock = threading.Lock()',
    '',
    '# ── Lazy DB import (avoids circular imports) ──────────────────────────',
    '_db_save = None',
    'def _get_db_save():',
    '    global _db_save',
    '    if _db_save is None:',
    '        try:',
    '            from capture.database import save_event',
    '            _db_save = save_event',
    '        except Exception:',
    '            _db_save = lambda e: None',
    '    return _db_save',
    '',
    '_handler = colorlog.StreamHandler()',
    '_handler.setFormatter(colorlog.ColoredFormatter(',
    '    fmt="%(log_color)s%(asctime)s%(reset)s [%(log_color)s%(levelname)-8s%(reset)s] %(cyan)s%(name)-10s%(reset)s %(message)s",',
    '    datefmt="%Y-%m-%d %H:%M:%S",',
    '    log_colors={"DEBUG":"white","INFO":"green","WARNING":"yellow","ERROR":"red","CRITICAL":"bold_red"}',
    '))',
    'logging.basicConfig(level=logging.INFO, handlers=[_handler])',
    '',
    'def get_logger(name: str):',
    '    return logging.getLogger(name)',
    '',
    'def log_event(service, attacker_ip, attacker_port, event_type, details=None):',
    '    event = {',
    '        "timestamp"    : datetime.now(timezone.utc).isoformat(),',
    '        "service"      : service,',
    '        "attacker_ip"  : attacker_ip,',
    '        "attacker_port": attacker_port,',
    '        "event_type"   : event_type,',
    '        "details"      : details or {},',
    '    }',
    '    # 1. Write to JSONL',
    '    with _file_lock:',
    '        with open(LOG_FILE, "a", encoding="utf-8") as f:',
    '            f.write(json.dumps(event) + "\\n")',
    '    # 2. Write to DB',
    '    try:',
    '        _get_db_save()(event)',
    '    except Exception as e:',
    '        get_logger("logger").debug(f"DB save failed: {e}")',
    '    # 3. Console',
    '    get_logger(service).info(f"[{event_type}] {attacker_ip}:{attacker_port} | {details}")',
    '    return event',
]))

# ── capture/__init__.py ───────────────────────────────────────────────────────
write('capture/__init__.py', '# capture package\n')

print("\nAll Phase 2 files written successfully!")
print("\nNext steps:")
print("  1. python main.py          — run honeypot (events now save to DB)")
print("  2. python capture/exporter.py  — export dataset to data/dataset.csv")
print()
